
:My name: Jeffrey B. Daube

= Hands-on Software Engineering with Golang
by {Achilleas Anagnostopoulos}

== Birds eye view of Software Engineering

DevOps is one of the most recently created Software Development Model (SDM)

As teams transition from monolithic to service-oriented arhcitectures (SoA), each engineering team owns the services they build---including both development and operations

*Two main DevOps models:*

1. Culture, Automation, Measurement, and Sharing (CAMS)
2. The three ways model

== Best Practices for Maintainable and Testible Go Code

Best practices tend to have a measurable positive effect on the code quality metrics associated with a code base and at the same time aid in minimizing the accumulation of technical debt.

*SOLID principles of object-oriented design*

_S_ - Single responsibility principle (SRP)

coined by Robert Martin ("Uncle Bob")

[quote, Robert Martin]
In any well-designed system , objects should only have a single responsibility

Object implementations should focus on doing one thing well, and in an efficient way

_O_ - Open/closed

coined by Betrand Meyer

[quote, Betrand Meyer]
A software module should be open for extension but closed for modification

Golang does not support inheritance; that leaves composition as the only viable approach for extending existing code

_L_ - Liskov substitution principle

coined by Barbara Liskov

[quote, Barbara Liskov]
If, for each object, 01 of type s there is an object 02 of type t such that for all programs p defined in terms of t, the behavior of p is unchanged when 01 is substituted for 02, then s is a subtype of t

Two types are substituteable if their exhibited behavior follow exactly the same contract, thereby making it impossible for the callers to distinguish between them

Golang does not support the concept of classes or inheritance but instead relies on interfaces as the means for facilitating type substitutions

Golang interfaces are implicit:: Each go type defines an implicit interface consisting of all the methods it implements.

_I_ - Interface segregation principle

coined by Robert Martin

clients should not be forced to depend upon the interfaces that they do not use

[quote, Rob Pike]
The bigger the interface, the weaker the abstraction

_D_ - Dependency inversion principle

High-level modules should not depend on low-level modules.
Both should depend on abstractions.
Abstractions should not depend on details.
Details should not depend on abstractions.

== Organize code into packages

Naming conventions for packages:: Go package names should be short and concise and provide a clear indication of their purpose to the intended users of the package

== Tips and tools for writing lean and easy-to-maintain Go code

1. Optimize function implementations for readability
2. Variable naming conventions - just long enough
3. Use Go interfaces effectively
4. Zero values are your friends (each type is automatically assigned its zero value when it gets instantiated)
5. Use tools to analyze and manipulate Go programs (abstract syntax trees ASTs)

[quote, Jack Lindamood]
Accept interfaces, return structs

== Dependency Management

[quote, Pat Rice]
If at first you don't suceed, call it version 1.0.

Semantic versioning:: is a widely popular system for describing software versions in a way that makes it quite straightforward for the intended software users to figure out which versions contain breaking API changes and therfore require development effort and time when upgrading

Major.minor.patch

== The Art of Testing

[quote, Edsger Dijkstra]
Program testing can be used to show the presence of bugs, but never to show their absence!

Unit test:: the smallest possible big of code that we can test

stub:: is the simplest test pattern that we can use in our tests

Stubs typically implement a particular interface and don't contain any real logic

spy:: is a stub that keeps a detailed log of all the methods that are invoked on it

ResponseRecorder type

mocks:: stubs on steroids

== System component modeling

UML Component diagram

main goal is to identify and describe the structural connections between the various components that comprise our system

[quote, author of this book]
A component is defined as an encapsulated standalone unit that constitutes an integral part of a system or a sub-system.  Components communicate with each other by exposing and consuming one or several interfaces.  One key point of component-based design is that components should always be considered as abstract, logical entities that epxose a particular behavior.

Command Query Responsibility Segregation (CQRS)::  An architectural pattern that separates the write and the read models exposed by a specific component so they can be optimized in isolation

Proxy design pattern:: connect components without introducing any coupling between their concrete implementations

== Building a Persitence Layer

[quote, Robert C. Martin]
Database schemas are notoriously volatile, extremely concrete, and highly depended on.  This is one reason why the interface between OO applications and databases is so difficult to manage, and why schema updates are generally painful.

*ACID*

Atomicity:: Transactions are applied completely or not at all
Consistency:: The contents of a transaction is not allowed to bring the database into an invalid state
Isolation:: Each transaction must execute in total isolation from other transactions
Durability:: Once a transaction has been committed, it will remain committed, even if system goes down